// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6I1UHPdK4jb3Jk5c8vdaUhuvlBrouRgg',
    appId: '1:344895159679:web:f874b4ad2cf35e5db06e4a',
    messagingSenderId: '344895159679',
    projectId: 'beergame-a4b61',
    authDomain: 'beergame-a4b61.firebaseapp.com',
    storageBucket: 'beergame-a4b61.firebasestorage.app',
    measurementId: 'G-QV0NF0KPF1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4xFZKkKWBJgz5tpbYO-pIuoTJxp0KPdw',
    appId: '1:344895159679:android:4cde43ef7cb3773db06e4a',
    messagingSenderId: '344895159679',
    projectId: 'beergame-a4b61',
    storageBucket: 'beergame-a4b61.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5Lzg01AZHrNTYZgSxSckiUeVKGYTNOwk',
    appId: '1:344895159679:ios:e9fd23e3da648cb4b06e4a',
    messagingSenderId: '344895159679',
    projectId: 'beergame-a4b61',
    storageBucket: 'beergame-a4b61.firebasestorage.app',
    iosBundleId: 'com.example.cloudflareTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5Lzg01AZHrNTYZgSxSckiUeVKGYTNOwk',
    appId: '1:344895159679:ios:e9fd23e3da648cb4b06e4a',
    messagingSenderId: '344895159679',
    projectId: 'beergame-a4b61',
    storageBucket: 'beergame-a4b61.firebasestorage.app',
    iosBundleId: 'com.example.cloudflareTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6I1UHPdK4jb3Jk5c8vdaUhuvlBrouRgg',
    appId: '1:344895159679:web:f7bd3c130bbee595b06e4a',
    messagingSenderId: '344895159679',
    projectId: 'beergame-a4b61',
    authDomain: 'beergame-a4b61.firebaseapp.com',
    storageBucket: 'beergame-a4b61.firebasestorage.app',
    measurementId: 'G-7MTT04MXL8',
  );
}
